COPTS = []

COMMON_DEPS = [
    "//:boom",
    "//:boom_test_utils",
    "@gtest//:gtest_main",
]

cc_test(
    name = "array_test",
    srcs = ["array_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "Cholesky_test",
    srcs = ["Cholesky_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "diagonal_matrix_test",
    srcs = ["diagonal_matrix_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "Eigen_test",
    srcs = ["Eigen_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "LU_test",
    srcs = ["LU_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "Matrix_test",
    srcs = ["Matrix_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "SpdMatrix_test",
    srcs = ["SpdMatrix_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "QR_test",
    srcs = ["QR_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "selector_test",
    srcs = ["selector_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "SVD_test",
    srcs = ["SVD_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,)

cc_test(
    name = "sweep_test",
    srcs = ["sweep_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "tail_test",
    srcs = ["tail_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "Vector_test",
    srcs = ["Vector_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)

cc_test(
    name = "VectorView_test",
    srcs = ["VectorView_test.cc"],
    copts = COPTS,
    deps = COMMON_DEPS,
)
