COPTS = [
    "-I/usr/local/include",
]

cc_test(
    name = "Cholesky_test",
    srcs = ["Cholesky_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "Eigen_test",
    srcs = ["Eigen_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "Matrix_test",
    srcs = ["Matrix_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "SpdMatrix_test",
    srcs = ["SpdMatrix_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "QR_test",
    srcs = ["QR_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "SVD_test",
    srcs = ["SVD_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "tail_test",
    srcs = ["tail_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "Vector_test",
    srcs = ["Vector_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)

cc_test(
    name = "VectorView_test",
    srcs = ["VectorView_test.cc"],
    copts = COPTS,
    deps = [
        "//:boom",
        "@gtest//:main",
    ],
)
