#!/bin/bash

# Run all tests for the BOOM C++ library.  This is a simple wrapper around the
# 'bazel test' command.  You can pass bazel flags such as 'testall -c opt' or
# 'testall -c dbg'

bazel test $* Models/... cpputil/... LinAlg/... Samplers/... stats/... distributions/...

# test comment
