# Copyright 2021 Steven L. Scott. All Rights Reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA


SimulateFakeClickstreamParams <- function (S2, S1, S0) {
  ## Simulate a list containing the parameters for a NestedHmm
  ## clickstream model.
  ## Args:
  ##   S2:  Dimension of the session-level hidden state.
  ##   S1:  Dimension of the click-level hidden state.
  ##   S0:  Dimension of the state space for observed data.
  ##
  ## Returns:
  ## A list containing initial distributions and transition
  ## probability matrices for a model of the specified dimensions.
  ## Each probability distribution is sampled from the uniform
  ## Dirichlet distribution of the appropriate dimension.

  rdir <- function (n, nu) {
    ## Simulate n draws from the Dirichlet distribution with prior count
    ## vector nu.
    d <- length(nu)
    ans <- t(matrix(rgamma(n * d, nu), nrow = d, ncol = n))
    tot <- apply(ans, 1, sum)
    ans/tot
  }

  Phi2 <- rdir(S2, rep(1, S2))
  phi2 <- rdir(1, rep(1, S2))
  Phi1 <- array(dim = c(S2, S1, S1))
  for (H in 1:S2) Phi1[H, , ] <- rdir(S1, rep(1, S1))
  phi1 <- rdir(S2, rep(1, S1))
  Phi0 <- array(dim = c(S2, S1, S0, S0))
  phi0 <- array(dim = c(S2, S1, S0))
  for (H in 1:S2) {
    for (h in 1:S1) {
      Phi0[H, h, , ] <- rdir(S0, rep(1, S0))
      phi0[H, h, ] <- c(rdir(1, rep(1, S0-1)), 0)
    }
  }
  ans <- list(Phi2 = Phi2, phi2 = phi2, Phi1 = Phi1, phi1 = phi1,
              Phi0 = Phi0, phi0 = phi0)
  return(ans)
}

SimulateClickstream <- function (number.of.streams, params = NULL,
                                 mean.session.size, S2, S1, S0)
{
  ## Simulate a fake data set from the nested HMM of the given
  ## dimension.
  ## Args:
  ##   number.of.streams: The number of clickstreams to simulate.
  ##     (I.e. the number of 'users'.)
  ##   params: If non-NULL, A list containing initial distributions
  ##     and transition probability matrices for the nested HMM.  If
  ##     NULL then params will be generated by a call to
  ##     SimulateFakeClickstreamParams.
  ##   mean.session.size: The expected number of sessions per
  ##     clickstream.
  ##   S2: The dimension of the session-level hidden Markov chain.
  ##     Only used if params is NULL.
  ##   S1: The dimension of the click-level hidden Markov chain.
  ##     Only used if params is NULL.
  ##   S0: The dimension (number of unique values) in the observed
  ##     data.  Only used if params is NULL.
  ##
  ## Returns:
  ##   A list of 2 elements.
  ##   * A list contaiing 'number.of.streams' clickstreams.
  ##   * A list containing the true parameter values used in the
  ##     simulation.  If params is non-NULL then this is 'params'.
  ##     Otherwise it is the set of simulated parameters.
  if (is.null(params)) {
    params <- SimulateFakeClickstreamParams(S2, S1, S0)
  }

  d <- dim(params$Phi0)
  S2 <- d[1]
  S1 <- d[2]
  S0 <- d[3]
  sessions.per.stream <- rpois(number.of.streams, mean.session.size)
  streams <- list()
  for (i in 1:number.of.streams) {
    number.of.sessions <- sessions.per.stream[i]
    sessions <- list();
    H <- sample(1:S2, size = 1, prob = params$phi2)
    time <- 0
    for (j in 1:number.of.sessions) {
      events <- numeric(0)
      h <- sample(1:S1, size = 1, prob = params$phi1[H, ])
      y <- sample(1:S0, size = 1, prob = params$phi0[H, h, ])
      events <- c(events, y)
      while (y != S0) {
        h <- sample(1:S1, size = 1, prob = params$Phi1[H, h, ])
        y <- sample(1:S0, size = 1, prob = params$Phi0[H, h, y, ])
        events <- c(events, y)
      }
      sessions[[length(sessions) + 1]] <- factor(events, levels = as.character(1:S0))
      H <- sample(1:S2, size = 1, prob = params$Phi2[H, ])
    }
    streams[[length(streams) + 1]] <- sessions
  }
  ans <- list(streams = streams, params = params)
  return(ans)
}
