#!/bin/bash

usage () { echo "Usage: $0 [-c] [-i] 1>&2; exit 0"; }

DO_INSTALL=0
DO_CHECK=0

while getopts :ci option; do
    case "${option}" in
        i)
            DO_INSTALL=1
            ;;
        c)
            DO_CHECK=1
            ;;
        \?)
	    echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done
shift $((OPTIND-1))

## If the rpackage directory does not exist then create it.
if [ ! -d rpackage ]; then
    mkdir rpackage
fi

BSTSDIR='rpackage/bsts'
## If there is already an rpackage/bsts directory then delete it.
if [ -d "$BSTSDIR" ]; then
   rm -rf $BSTSDIR
fi

cp -r ./Interfaces/R/bsts rpackage
cd rpackage
if [ -d bsts/tests ]; then
    if [ ! -d bsts/inst ]; then
	mkdir bsts/inst
    fi
    mv bsts/tests bsts/inst/tests
fi

if [ -f bsts_*.tar.gz ]; then
    rm bsts_*.tar.gz
fi

R CMD BUILD bsts

if [[ $DO_CHECK = 1 ]]; then
    echo "Checking package"
    MAKEFLAGS=" -j 8 " R CMD CHECK bsts_*.tar.gz
fi

if [[ $DO_INSTALL = 1 ]]; then
    echo "Installing package"
    MAKEFLAGS=" -j 8 " R CMD INSTALL bsts_*.tar.gz
fi
